apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: ai-flow-timescaledb:5432
    database: telemetry
    user: postgres
    editable: true
    secureJsonData:
      password: postgres
    jsonData:
      database: telemetry
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400